fixed some issues
Hubmakerlabs/suiguild-webapp pull request #12
Opened 2023-07-19 19:00 UTC by marc0129

2023-07-28 08:31 UTC, Slmii requested changes

2023-07-28 08:31 UTC, Slmii commented on package.json
> +		"moment": "^2.29.4",
can we use another date package? moment is deprecated and too large. Dayjs or datefns is a good alternative

2023-07-28 08:31 UTC, Slmii commented on src/components/LanguageSelector/LanguageSelector.tsx
> +import { makeStyles } from '@mui/styles';
why are we still using the legacy/deprecated styles packages for new components??

2023-07-28 08:31 UTC, Slmii commented on src/components/Tabs/Tabs.component.tsx
> +				gap: '9px',
hardcoded pixels. why arent we using MUI theme's spacings

2023-07-28 08:31 UTC, Slmii commented on src/helpers/date.helpers.ts
> +	let current = moment(Date.now());
deprecated moment package, good alternative is dayjs or datefns

2023-07-28 08:31 UTC, Slmii commented on src/views/Dashboard/components/Main.tsx
> +	useEffect(() => {
does this useEffect works as expected? It has no dependency so `posts` will always be undefined when this useEffect runs?

2023-07-28 08:31 UTC, Slmii commented on src/views/Dashboard/components/PostCard/index.tsx
> +	const follow_community = async (fId: number) => {
lets stay consistent when function names. use `camelCase` everywhere

2023-07-28 08:31 UTC, Slmii commented on src/views/Dashboard/components/PostCard/index.tsx
> +	const vote_post = async (pId: number) => {
here as well

2023-07-28 08:31 UTC, Slmii commented on src/views/Dashboard/components/TrendingForumsCard.tsx
> +	const follow_community = async (fId: number) => {
function naming

2023-07-28 08:31 UTC, Slmii commented on src/views/Forum/components/CommunityIndividual/CommunitiesCard.tsx
> +			setFilteredForums(forums);
why do we need a seperate useState for this? Why not just use the values directly from the useSWR call

2023-07-28 08:31 UTC, Slmii commented on src/views/Forum/components/CommunityIndividual/Main.tsx
> +		setFilteredPosts(filteredTmpPosts);
same goes for this. we can just have derived values instead of seperate useStates for filterss/searched

2023-07-28 08:31 UTC, Slmii commented on src/views/Forum/components/CommunityIndividual/OtherPopularCommunitiesCard.tsx
> +			setPopularForums(resultForums);
same here, we can use derived values instead of seperate useStates

```
const { forums } = useContext(ForumContext);

const popularForums = useMemo(() => {
    if (!forums) {
        return []
    }
    
    const filteredForums = forums.filter(forum => forum.num_post > 0);
    return filteredForums.slice(0, 5);
}, [forums])
```

Same goes for all others

2023-07-28 08:31 UTC, Slmii commented on src/views/Forum/components/PostCard/Comment.tsx
> +			await create_reply(
are we updating caches after a mutation?

2023-07-28 08:31 UTC, Slmii commented on src/views/Forum/components/TrendingPostsCard.tsx
> +	useEffect(() => {
derived values

2023-07-28 08:31 UTC, Slmii commented on src/views/Profile/components/EditProfileLayout.tsx
> +					padding: iMd ? '18px auto' : '18px 150px'
hardcoded pixels, can we use MUI theme's spacings

2023-07-28 08:43 UTC, marc0129 commented on package.json
> +		"moment": "^2.29.4",
okay. Will change another date package.

2023-07-28 15:24 UTC, marc0129 commented on src/helpers/date.helpers.ts
> +	let current = moment(Date.now());
okay, got you.

2023-07-28 15:59 UTC, marc0129 commented on src/components/Tabs/Tabs.component.tsx
> +				gap: '9px',
fixed

2023-07-28 16:16 UTC, marc0129 commented on src/views/Dashboard/components/Main.tsx
> +	useEffect(() => {
yep, fixed issue.

2023-07-28 16:18 UTC, marc0129 commented on src/views/Dashboard/components/PostCard/index.tsx
> +	const follow_community = async (fId: number) => {
fixed

2023-07-28 16:18 UTC, marc0129 commented on src/views/Dashboard/components/PostCard/index.tsx
> +	const vote_post = async (pId: number) => {
fixed

2023-07-28 16:18 UTC, marc0129 commented on src/views/Dashboard/components/TrendingForumsCard.tsx
> +	const follow_community = async (fId: number) => {
fixed

2023-08-01 06:56 UTC, marc0129 commented on src/views/Profile/components/EditProfileLayout.tsx
> +					padding: iMd ? '18px auto' : '18px 150px'
fixed

2023-08-01 06:57 UTC, marc0129 commented on src/views/Forum/components/CommunityIndividual/Main.tsx
> +		setFilteredPosts(filteredTmpPosts);
fixed

2023-08-01 07:09 UTC, marc0129 commented on src/views/Forum/components/CommunityIndividual/OtherPopularCommunitiesCard.tsx
> +			setPopularForums(resultForums);
fixed

2023-08-01 13:39 UTC, marc0129 commented on src/views/Forum/components/CommunityIndividual/CommunitiesCard.tsx
> +			setFilteredForums(forums);
fixed

2023-08-01 13:39 UTC, marc0129 commented on src/views/Forum/components/TrendingPostsCard.tsx
> +	useEffect(() => {
fixed

2023-08-01 13:40 UTC, marc0129 commented on src/views/Forum/components/PostCard/Comment.tsx
> +			await create_reply(
yep

2023-08-01 13:40 UTC, marc0129 commented on src/components/LanguageSelector/LanguageSelector.tsx
> +import { makeStyles } from '@mui/styles';
fixed

2023-08-03 09:51 UTC, Slmii approved these changes

2023-08-03 09:52 UTC, Slmii commented
@Ben-Everard LGTM

2023-08-07 09:51 UTC, merged