Fix bugs part 2
Hubmakerlabs/suiguild-webapp pull request #26
Opened 2023-11-07 16:24 UTC by Electr1Xx

2023-11-13 09:41 UTC, Slmii requested changes

2023-11-13 09:41 UTC, Slmii commented on src/components/UsernameDialog/UsernameDialog.tsx
> +		setIsLodaing(true);
type in setter

2023-11-13 09:41 UTC, Slmii commented on src/views/Forum/components/TrendingPostsCard.tsx
> +										<Link component={NavLink} to={`/forum/postindividual/${post.idx}`} sx={{ textDecoration: 'none' }}>
perhaps set the textDecoration as default to `none` in theming

2023-11-14 08:26 UTC, Electr1Xx commented on src/components/UsernameDialog/UsernameDialog.tsx
> +		setIsLodaing(true);
added

2023-11-14 08:26 UTC, Electr1Xx commented on src/views/Forum/components/TrendingPostsCard.tsx
> +										<Link component={NavLink} to={`/forum/postindividual/${post.idx}`} sx={{ textDecoration: 'none' }}>
fixed

2023-11-14 09:55 UTC, Slmii approved these changes

2023-11-14 09:55 UTC, merged