Fix/wallet
Hubmakerlabs/suiguild-webapp pull request #27
Opened 2023-11-08 12:00 UTC by marc0129

2023-11-08 14:20 UTC, Slmii requested changes

2023-11-08 14:20 UTC, Slmii commented on src/views/Profile/index.tsx
> +		[id]
seems like an unncessary `useMemo`, is the `id` is not being used here

2023-11-08 14:20 UTC, Slmii commented on src/views/Profile/index.tsx
> +										width: theme => theme.spacing(25),
FYI you can also just use `25` for MUI components, MUI will use proper spacing under the hood

2023-11-08 14:20 UTC, Slmii commented on src/views/Settings/components/EditProfile.tsx
> +		if (profile?.display_name == '') {
can we not check against an empty string? just use `!x`

2023-11-08 14:20 UTC, Slmii commented on src/views/Settings/components/EditProfile.tsx
> +		if (profile?.display_name == '') {
also lets use `===` everywhere because `1 == '1' // true`

2023-11-08 14:20 UTC, Slmii commented on src/views/Wallet/Transfer/components/SendNFT.tsx
> +				//  onClick={() => setOpen(true)}
remove comment

2023-11-08 14:20 UTC, Slmii commented on src/views/Wallet/Transfer/components/SendToken.tsx
> +									<KeyboardArrowUpIcon sx={{ cursor: 'pointer' }} onClick={visibleChange} />
icons are not really meant to be interactive, better to use IconButtons

2023-11-08 14:20 UTC, Slmii commented on src/views/Wallet/components/Activity.tsx
> +			return transferedTransactions.filter((txn: any) => regex.test(txn.balanceChanges![1].owner.AddressOwner));
lets not use `any` as type

2023-11-08 14:20 UTC, Slmii commented on src/views/Wallet/components/Activity.tsx
> +				filteredTransactions.map((transaction: any, index: number) => (
`any` type

2023-11-08 14:20 UTC, Slmii commented on src/views/Wallet/index.tsx
> +							color: '#BB9BFF'
will these hardcoded colors not cause issues with dark/light mode?

2023-11-08 14:20 UTC, Slmii commented on src/components/ToggleButtonGroup/ToggleButtonGroup.components.tsx
> +					key={index}
lets not use `index` from maps as keys https://robinpokorny.com/blog/index-as-a-key-is-an-anti-pattern/

2023-11-08 14:20 UTC, Slmii commented on src/hooks/useProfile.ts
> +	const check_username = async (display_name: string) => {
naming convensions

2023-11-08 14:57 UTC, marc0129 commented on src/components/Layout/Header/Header.component.tsx
> +	const { create_community } = useGilder();
fixed

2023-11-08 15:01 UTC, marc0129 commented on src/views/Forum/components/CommunityIndividual/index.tsx
> +			if (data.visibility == 'private') {
fixed

2023-11-08 15:09 UTC, marc0129 commented on src/hooks/useProfile.ts
> +	const check_username = async (display_name: string) => {
fixed

2023-11-08 15:14 UTC, marc0129 commented on src/views/Wallet/index.tsx
> +							color: '#BB9BFF'
fixed

2023-11-08 15:16 UTC, marc0129 commented on src/views/Home/components/ForumCard.tsx
> +						{' '}
fixed

2023-11-08 15:18 UTC, marc0129 commented on src/views/Home/index.tsx
> +	const { check_username } = useProfile();
fixed

2023-11-08 15:27 UTC, marc0129 commented on src/views/Profile/components/ProfilePosts.tsx
> +						sx={{ cursor: 'pointer', overflow: 'hidden', textOverflow: 'ellipsis', width: '100%' }}
fixed

2023-11-08 15:33 UTC, marc0129 commented on src/views/Profile/index.tsx
> +		[id]
fixed

2023-11-08 15:36 UTC, marc0129 commented on src/views/Wallet/Transfer/components/SendNFT.tsx
> +				//  onClick={() => setOpen(true)}
fixed

2023-11-08 15:43 UTC, marc0129 commented on src/views/Wallet/Transfer/components/SendToken.tsx
> +									<KeyboardArrowUpIcon sx={{ cursor: 'pointer' }} onClick={visibleChange} />
fixed

2023-11-08 15:48 UTC, marc0129 commented on src/components/ToggleButtonGroup/ToggleButtonGroup.components.tsx
> +					key={index}
fixed using option.value

2023-11-09 09:08 UTC, marc0129 commented on src/App.tsx
> +const ScrollToTop = () => {
fixed

2023-11-09 13:26 UTC, marc0129 commented on src/views/Settings/components/EditProfile.tsx
> +		if (profile?.display_name == '') {
fixed

2023-11-09 13:48 UTC, marc0129 commented on src/views/Dashboard/components/PostCard/index.tsx
> +	const shareLink =
fixed

2023-11-09 13:50 UTC, marc0129 commented on src/views/Home/index.tsx
> +				setLodaing(false);
fixed

2023-11-09 17:17 UTC, marc0129 commented on src/views/Wallet/components/Activity.tsx
> +				filteredTransactions.map((transaction: any, index: number) => (
fixed

2023-11-09 18:19 UTC, Slmii requested changes

2023-11-09 18:19 UTC, Slmii commented on src/components/Layout/Header/Header.component.tsx
> +						action={data => console.log(data)}
why is the action removed?

2023-11-09 18:19 UTC, Slmii commented on src/views/Forum/components/CommunityIndividual/index.tsx
> +		if (isFollowing === undefined) {
`!isFollowing` or change `find` to `some` so we have a boolean value, might be. better to work with

2023-11-09 18:19 UTC, Slmii commented on src/views/Home/index.tsx
>  				setLodaing(false);
typo is on the state setter `setLodaing`

2023-11-09 18:19 UTC, Slmii commented on src/views/ProfileGames/ProfileGameForm.tsx
>  					console.log(searchValue);
remove logs

2023-11-09 18:21 UTC, marc0129 commented on src/components/Layout/Header/Header.component.tsx
> +						action={data => console.log(data)}
Because it doesn't do anything for now.

2023-11-10 11:56 UTC, marc0129 commented on src/views/Forum/components/CommunityIndividual/index.tsx
> +		if (isFollowing === undefined) {
fixed

2023-11-10 11:57 UTC, marc0129 commented on src/views/ProfileGames/ProfileGameForm.tsx
>  					console.log(searchValue);
removed

2023-11-10 13:24 UTC, Slmii approved these changes

2023-11-10 13:34 UTC, merged