Fix bugs part 3
Hubmakerlabs/suiguild-webapp pull request #28
Opened 2023-11-15 07:55 UTC by Electr1Xx

2023-11-16 20:56 UTC, Slmii requested changes

2023-11-16 20:56 UTC, Slmii commented on src/views/Forum/components/CommunityIndividual/Main.tsx
> +type SortKey = 'comments' | 'new' | 'votes';
exact same type as above, move it where it can be used multiple times

2023-11-16 20:56 UTC, Slmii commented on src/views/Forum/components/Main.tsx
> +type CommunitySortKey = 'comments' | 'new' | 'posts';
same here, is a shared type

2023-11-16 20:56 UTC, Slmii commented on src/views/Forum/components/Main.tsx
> +	const handleCommunitySortChange = useCallback((sortVal: CommunitySortKey) => {
do we need to wrap everything in a useCallback? its not heavy and react is fast enough by itself. seems unncessary to wrap every fn with useCallback.

what you think

2023-11-16 20:56 UTC, Slmii commented on src/views/Forum/components/Main.tsx
>  	];
move it outside the component if its not being changed

2023-11-16 20:56 UTC, Slmii commented on src/views/Profile/components/Awards.tsx
>  					borderRadius: theme => `${theme.shape.borderRadius}px`,
``borderRadius: theme => `${theme.shape.borderRadius}px`,`` > `borderRadius: 1`

2023-11-16 20:56 UTC, Slmii commented on src/views/Profile/components/ProfilePosts.tsx
> +											(iPost: IPost, index: number) => index > 1 && <PostCard key={index} details={iPost} />
we can use inferred types, dont need explicit types with simple stuff

2023-11-17 09:03 UTC, Electr1Xx commented on src/views/Forum/components/Main.tsx
>  	];
I think we need to keep it in the component because it's related only to this component and can be unique for example we can change the label, or add an icon

2023-11-17 09:05 UTC, Slmii commented on src/views/Forum/components/Main.tsx
>  	];
i meant more like keep is inside the same file but outside the component? let me know what you think

2023-11-17 09:07 UTC, Electr1Xx commented on src/views/Forum/components/Main.tsx
>  	];
yea we can move it

2023-11-17 10:27 UTC, Slmii approved these changes

2023-11-17 11:29 UTC, merged