Sprint8
Hubmakerlabs/suiguild-webapp pull request #68
Opened 2024-01-30 08:07 UTC by marc0129

2024-02-06 06:49 UTC, Slmii requested changes

2024-02-09 12:07 UTC, marc0129 commented on src/api/message.ts
> +	console.log(response.data);
fixed. and this is for upcoming function

2024-02-09 12:25 UTC, marc0129 commented on src/components/Badge/Badge.component.tsx
> +	return badgeContent === '0' ? (
fixed

2024-02-12 13:33 UTC, Slmii requested changes

2024-02-12 13:33 UTC, Slmii commented on src/components/ImageField/ImageField.component.tsx
> +								<Box
missing a `key`

2024-02-12 13:33 UTC, Slmii commented on src/components/ImageUpload/ImageUpload.tsx
> +										<Box>
is the `Box` elements required?

2024-02-12 13:33 UTC, Slmii commented on src/views/Forum/components/Chat/ChatCard/Members.tsx
> +				sx={{ width: 'auto', ':hover': { boxShadow: 'none' } }}
its not `&:hover`?

2024-02-12 13:33 UTC, Slmii commented on src/views/Forum/components/Chat/ChatCard/Members.tsx
> +	}, [getUsernames, getUserByName, customFilter]);
isnt is nicer to put this in a SWR hook?

2024-02-12 13:33 UTC, Slmii commented on src/views/Forum/components/Chat/ChatCard/Members.tsx
> +		(member: string) => membersField.value.some((user: string) => user === member),
unecessary type `(user: string)`?

2024-02-12 13:33 UTC, Slmii commented on src/views/Forum/components/Chat/ChatCard/Members.tsx
> +	const handleMembers = (member: string) => {
maybe more specific with the fn name, handle members doing what?

2024-02-12 13:33 UTC, Slmii commented on src/views/Forum/components/Chat/ChatCard/Members.tsx
> +	const friends = (() => {
wouldnt a normal function or useMemo be nicer instead of IIFE?

2024-02-12 13:33 UTC, Slmii commented on src/views/Forum/components/Chat/ChatCard/Members.tsx
> +				{friends.map((username: string) => (
`friends` should be typed already?

2024-02-12 13:33 UTC, Slmii commented on src/views/Notifications/index.tsx
> +						notifications.map((notification, index) => <NotificationCard detail={notification} key={index} />)
use a sort of `id` as key instead of `index`

2024-02-12 14:34 UTC, Electr1Xx commented on src/views/Forum/components/Chat/ChatCard/Members.tsx
> +	const friends = (() => {
Because we don’t have large calculations here and it doesn’t make sense to use useMemo

2024-02-12 15:21 UTC, Slmii approved these changes

2024-02-12 15:22 UTC, merged