chat redesign
Hubmakerlabs/suiguild-webapp pull request #82
Opened 2024-02-21 09:09 UTC by revomhere

2024-02-21 09:29 UTC, Electr1Xx commented on src/components/Avatar/Avatar.component.tsx
> +				width: theme => theme.spacing(5),
use CustomAvatar

2024-02-21 09:29 UTC, Electr1Xx commented on src/index.css
> +	padding: 0 !important;
remove

2024-02-21 09:29 UTC, Electr1Xx commented on src/views/Forum/components/Chat/ChatCard/ChatCard.tsx
> +				padding: theme.spacing(1),
remove makeStyles and use styled instead

2024-02-21 09:29 UTC, Electr1Xx commented on src/views/Forum/components/Chat/ChatCard/ChatCard.tsx
> +				padding: theme.spacing(1),
padding: 1

2024-02-21 09:29 UTC, Electr1Xx commented on src/views/Forum/components/Chat/ChatCard/ChatCard.tsx
> +					borderRadius: theme.shape.borderRadius
1

2024-02-21 09:29 UTC, Electr1Xx commented on src/views/Forum/components/Chat/ChatCard/ChatCard.tsx
> +							gap: iSm ? theme => theme.spacing(1.5) : theme => theme.spacing(0)
optimize

2024-02-21 09:29 UTC, Electr1Xx commented on src/views/Forum/components/Chat/ChatCard/ChatCard.tsx
> +									<Stack direction="row" alignItems="center" gap="12px">
gap={1.5}

2024-02-21 09:29 UTC, Electr1Xx commented on src/views/Forum/components/Chat/ChatCard/ChatCard.tsx
> +				<Box width={iSm ? `100%` : 200}>
``->''

2024-02-21 09:29 UTC, Electr1Xx commented on src/views/Forum/components/Chat/ChatCard/MessageField.tsx
> +						position: 'absolute',
why is position absolute?

2024-02-21 09:29 UTC, Electr1Xx commented on src/views/Forum/components/Chat/ChatCard/MessageField.tsx
> +				<Box sx={{ display: 'flex', gap: theme => theme.spacing(1.5) }}>
gap: 1.5 check all places and use Stack instead of Box for flex

2024-02-21 09:29 UTC, Electr1Xx commented on src/views/Forum/components/Chat/GroupChats.tsx
> +							placeholder="0/30"
maybe search?

2024-02-21 09:29 UTC, Electr1Xx commented on src/views/Forum/components/Chat/GroupChats.tsx
> +				padding: '12px 24px 12px 12px',
theme.spacing

2024-02-21 09:29 UTC, Electr1Xx commented on src/views/Forum/components/Chat/GroupInfoCard/GroupInfoCard.tsx
> +								sx={{ margin: `0 16px`, borderStyle: 'solid', borderColor: 'rgba(255, 255, 255, 0.15)' }}
1)theme.spacing
2) 255, 255, 255, 0.15 -> theme.palette.border.subtle

2024-02-21 09:29 UTC, Electr1Xx commented on src/views/Forum/components/Chat/GroupInfoCard/GroupInfoCard.tsx
> +							width: '56px',
!

2024-02-21 09:29 UTC, Electr1Xx commented on src/views/Forum/components/Chat/GroupInfoCard/GroupInfoCard.tsx
> +			<Box sx={{ padding: `0 16px 16px` }}>
!

2024-02-21 09:29 UTC, Electr1Xx commented on src/views/Forum/components/Chat/index.tsx
>  const useStyles = makeStyles((theme: Theme) => ({
remove

2024-02-21 09:29 UTC, Electr1Xx commented on src/views/Forum/components/Chat/index.tsx
> +						<Grid item lg={3} md={12} sm={12} xs={12} className={`chatCardsHeader-wrp`}>
className='chatCardsHeader-wrp'

2024-02-21 11:15 UTC, revomhere commented on src/components/Avatar/Avatar.component.tsx
> +				width: theme => theme.spacing(5),
+

2024-02-21 11:15 UTC, revomhere commented on src/index.css
> +	padding: 0 !important;
+

2024-02-21 11:39 UTC, revomhere commented on src/views/Forum/components/Chat/index.tsx
>  const useStyles = makeStyles((theme: Theme) => ({
+

2024-02-21 11:39 UTC, revomhere commented on src/views/Forum/components/Chat/index.tsx
> +						<Grid item lg={3} md={12} sm={12} xs={12} className={`chatCardsHeader-wrp`}>
+

2024-02-22 09:06 UTC, revomhere commented on src/views/Forum/components/Chat/GroupInfoCard/GroupInfoCard.tsx
> +							width: '56px',
+

2024-02-22 09:06 UTC, revomhere commented on src/views/Forum/components/Chat/GroupInfoCard/GroupInfoCard.tsx
> +								sx={{ margin: `0 16px`, borderStyle: 'solid', borderColor: 'rgba(255, 255, 255, 0.15)' }}
+

2024-02-22 09:06 UTC, revomhere commented on src/views/Forum/components/Chat/GroupChats.tsx
> +				padding: '12px 24px 12px 12px',
+

2024-02-22 09:07 UTC, revomhere commented on src/views/Forum/components/Chat/GroupChats.tsx
> +							placeholder="0/30"
+

2024-02-22 09:33 UTC, revomhere commented on src/views/Forum/components/Chat/ChatCard/MessageField.tsx
> +						position: 'absolute',
+

2024-02-22 09:33 UTC, revomhere commented on src/views/Forum/components/Chat/ChatCard/MessageField.tsx
> +				<Box sx={{ display: 'flex', gap: theme => theme.spacing(1.5) }}>
+

2024-02-22 09:50 UTC, revomhere commented on src/views/Forum/components/Chat/ChatCard/ChatCard.tsx
> +				<Box width={iSm ? `100%` : 200}>
+

2024-02-22 10:03 UTC, revomhere commented on src/views/Forum/components/Chat/ChatCard/ChatCard.tsx
> +									<Stack direction="row" alignItems="center" gap="12px">
+

2024-02-22 10:07 UTC, revomhere commented on src/views/Forum/components/Chat/ChatCard/ChatCard.tsx
> +							gap: iSm ? theme => theme.spacing(1.5) : theme => theme.spacing(0)
+

2024-02-23 11:56 UTC, Electr1Xx commented on src/views/Forum/components/Chat/ChatCard/MessageField.tsx
> +					<Box sx={{
need to discuss

2024-02-23 11:56 UTC, Electr1Xx commented on src/views/Forum/components/Chat/GroupChats.tsx
> +			...(iSm && {
!

2024-02-23 11:56 UTC, Electr1Xx commented on src/views/Forum/components/Chat/GroupChats.tsx
> +						height: 22
use theme.spacing instead of numbers and px

2024-02-23 11:56 UTC, Electr1Xx commented on src/views/Forum/components/Chat/GroupChats.tsx
> +				}
?

2024-02-23 11:56 UTC, Electr1Xx commented on src/views/Forum/components/Chat/GroupChats.tsx
> +	return <MediumAvatar image={user?.userInfo.some?.avatar.url ? ipfsUrl(user?.userInfo.some.avatar.url) : ''} sx={{
Custom avatar

2024-02-23 11:56 UTC, Electr1Xx commented on src/views/Forum/components/Chat/GroupChats.tsx
> +				padding: theme => theme.spacing(1.5),
1.5

2024-02-23 11:56 UTC, Electr1Xx commented on src/views/Forum/components/Chat/GroupInfoCard/GroupInfoCard.tsx
> +						{isLoaded ? (
why do we use 2 isLoaded?

2024-02-23 11:56 UTC, Electr1Xx commented on src/views/Forum/components/Chat/index.tsx
> +							className={`selectChat-wrp`}
!

2024-02-23 11:56 UTC, Electr1Xx commented on src/views/Forum/components/Chat/index.tsx
> +	padding: '28px 60px',
!

2024-02-23 12:12 UTC, Electr1Xx commented on src/views/Forum/components/Chat/index.tsx
> +							<Grid item lg={3} md={12} sm={12} xs={12} style={{paddingLeft: `0 !important`}}>
!

2024-02-26 11:17 UTC, Electr1Xx commented on src/views/Forum/components/Chat/ChatCard/ChatCard.tsx
> +					border: { xs: 'none', sm: `1px solid ${theme.palette.dark[700]}` }
theme.spacing(0.125)

2024-02-26 11:18 UTC, Electr1Xx commented on src/views/Forum/components/Chat/ChatCard/ChatCard.tsx
> +							gap: { xs: theme.spacing(1.5), sm: 0 }
try without theme.spacing

2024-02-26 11:18 UTC, Electr1Xx commented on src/views/Forum/components/Chat/ChatCard/MessageField.tsx
> +				padding: isChat ? theme.spacing(iSm ? 2 : 0, 2, 2, 2) : theme.spacing(0),
: 0

2024-02-26 11:19 UTC, Electr1Xx commented on src/views/Forum/components/Chat/ChatCard/MessageField.tsx
>  						borderRadius: '8px'
: 1

2024-02-26 11:21 UTC, Electr1Xx commented on src/views/Forum/components/Chat/ChatCard/Messages.tsx
> +				padding: iSm ? 0 : '16px',
: 2

2024-02-26 11:21 UTC, Electr1Xx commented on src/views/Forum/components/Chat/GroupChats.tsx
> +						marginRight: theme => theme.spacing(3),
xs: 0, sm: 3

2024-02-26 11:22 UTC, Electr1Xx commented on src/views/Forum/components/Chat/GroupChats.tsx
> +	paddingLeft: iSm ? theme.spacing(2) : 0,
use theme.breakpoints instead of iSm

2024-02-26 11:22 UTC, Electr1Xx commented on src/views/Forum/components/Chat/GroupChats.tsx
> +		borderBottom: `1px solid ${theme.palette.dark[500]}`
!

2024-02-26 11:23 UTC, Electr1Xx commented on src/views/Forum/components/Chat/GroupChats.tsx
> +			...(!iSm && {
remove iSm

2024-02-26 11:25 UTC, Electr1Xx commented on src/views/Forum/components/Chat/GroupInfoCard/GroupInfoCard.tsx
> +								sx={{ margin: theme => theme.spacing(0, 2), borderStyle: 'solid', borderColor: theme => theme.palette.border.subtle }}
you can use mx for margin left and right instead of margin

2024-02-26 11:25 UTC, Electr1Xx commented on src/views/Forum/components/Chat/GroupInfoCard/GroupInfoCard.tsx
> +		border: `1px solid ${theme.palette.dark[700]}`,
!

2024-02-26 11:25 UTC, Electr1Xx commented on src/views/Forum/components/Chat/GroupInfoCard/GroupInfoCard.tsx
> +			margin: '16px 17px',
!

2024-02-26 11:27 UTC, Electr1Xx commented on src/views/Forum/components/Chat/index.tsx
> +				// spacing={3}
why did you hide it ?

2024-02-26 11:30 UTC, Electr1Xx commented on src/views/Forum/components/Chat/index.tsx
> +	'& .chatCard-wrp': {
remove and use directly on the component

2024-02-26 11:31 UTC, Electr1Xx commented on src/views/Forum/components/Chat/index.tsx
> +							className='selectChat-wrp'
remove class names

2024-02-27 07:37 UTC, Electr1Xx requested changes

2024-02-27 07:37 UTC, Electr1Xx commented on src/views/Forum/components/Chat/ChatCard/ChatCard.tsx
> +		background: theme.breakpoints.down('xs') ? theme.palette.dark[700] : 'none',
```
[theme.breakpoints.down('xs')]: {
background: theme.palette.dark[700]
}
```

2024-02-27 07:37 UTC, Electr1Xx commented on src/views/Forum/components/Chat/ChatCard/MessageField.tsx
> +				padding: isChat ? theme.spacing(iSm ? 2 : 0, 2, 2, 2) : 0,
{xs: 2, sm: theme.spacing}

2024-02-27 07:37 UTC, Electr1Xx commented on src/views/Forum/components/Chat/ChatCard/Messages.tsx
> +				padding: iSm ? 0 : 2,
{xs: 0, sm:2}

2024-02-27 07:37 UTC, Electr1Xx commented on src/views/Forum/components/Chat/GroupChats.tsx
> +					marginRight: { xs: 0, sm: 3 },
move to class

2024-02-27 07:37 UTC, Electr1Xx commented on src/views/Forum/components/Chat/GroupInfoCard/GroupInfoCard.tsx
> +						left: theme => theme.spacing(10),
move to class

2024-02-27 07:41 UTC, Electr1Xx requested changes

2024-02-27 07:41 UTC, Electr1Xx commented on src/views/Forum/components/Chat/ChatCard/ChatCard.tsx
> +		background: theme.breakpoints.down('xs') ? theme.palette.dark[700] : 'none',
!

2024-02-27 09:00 UTC, Electr1Xx approved these changes

2024-02-27 09:17 UTC, ArtSuslov approved these changes

2024-02-27 09:17 UTC, ArtSuslov commented on src/components/Layout/Layout.component.tsx
> +		>
- boolean naming
- disableMaxWidth seems like redundant

```suggestion
		<Container
			maxWidth={isMaxWidth ? 'desktop' : false}
			className="main-container"
		>
```

2024-02-27 09:17 UTC, ArtSuslov commented on src/views/Forum/components/Chat/ChatCard/ChatCard.tsx
> +	maxHeight: 'calc(100vh - 100px)',
mb `100px` should be moved to a const?

2024-02-27 09:17 UTC, ArtSuslov commented on src/views/Forum/components/Chat/ChatCard/MessageField.tsx
> +							}
```suggestion
				fileRef.current?.click();
```

2024-02-27 09:17 UTC, ArtSuslov commented on src/views/Forum/components/Chat/ChatCard/MessageField.tsx
> +									if (fileRef.current) {
!

2024-02-27 09:17 UTC, ArtSuslov commented on src/views/Forum/components/Chat/GroupInfoCard/GroupInfoCard.tsx
> +										{lastActivity === '0' ? 'Online' : `Last seen ${differenceDate(Date.now() - lastActivity * 1000)}`}
mb add some tolerance to assume user is online? like 10-15 seconds

2024-02-27 09:23 UTC, merged